# Site settings
title: kai's Blog
SEOTitle: kai | kai's Blog
header-img: img/home-bg.jpg
email: fkai56525@gmail.com
description: "The youth, the scenery along the way again also is just a paper elegance. | 未来可期！"
keyword: "kai, 未来, 明天, 今天, 昨天, 你, 我, kai's blog, 博客, 个人网站, 互联网, Web, QU, 100001000, ART, 前端, 设计"
url: "https://https://space.bilibili.com/431820998" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: 羽书离弦啊
zhihu_username: 
github_username: fukaikai
twitter_username: 
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Livere来必力
labili: true
labili_uid: MTAyMC82MDExNy8zNjU4Mw==

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-WHLX4RQ31R" # Format: UA-xxxxxx-xx
ga_domain: auto

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "人生如逆旅，我亦是行人。 <br> ---苏轼---"
sidebar-avatar: https://ooo.0x0.ooo/2024/09/07/Ot3Xaq.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true

# Friends
friends:
  [
    { title: "纳西妲", href: "https://ooo.0x0.ooo/2024/09/07/Ot3sut.jpg" },
    { title: "纳西妲", href: "https://ooo.0x0.ooo/2024/09/07/Ot3YFx.jpg" },
    { title: "my bilibili", href: "https://space.bilibili.com/431820998" },
    { title: "else", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "my senior high school", href: "https://www.ts1z.cn/index" },
    { title: "女朋友", href: "https://ooo.0x0.ooo/2024/09/07/Ot3fPj.jpg" },
  ]
